# Generated by Django 4.1.4 on 2023-02-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='accepted',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
