# Generated by Django 4.1.4 on 2023-02-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friends_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='accepted',
            new_name='is_accepted',
        ),
    ]
