# Generated by Django 4.1.4 on 2023-03-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_message_data_created_alter_user_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
    ]
